### ISSUE TITLE
TweetScraper

### ISSUE THREAD

**Issue by nurdi1995** [jonbakerfish/TweetScraper#103]
ModuleNotFoundError: No module named 'TweetScraper'

**Comment by HarrisonHHH** [comment]
Could you tell me how you solved it?

**Comment by nurdi1995** [comment]
finish about what? can you explain

Pada Jum, 13 Sep 2024 pukul 12.29 HarrisonHHH ***@***.***>
menulis:

**Comment by HarrisonHHH** [comment]
Hi jonbakerfish,




Thank you for your time.




I encountered a new problem, which is 




(base) ***@***.*** TweetScraper % scrapy crawl TweetScraper -a query="foo,#bar"

2024-09-13 14:37:41 [scrapy.utils.log] INFO: Scrapy 2.8.0 started (bot: TweetScraper)

2024-09-13 14:37:41 [scrapy.utils.log] INFO: Versions: lxml 4.9.2.0, libxml2 2.10.3, cssselect 1.1.0, parsel 1.6.0, w3lib 1.21.0, Twisted 22.10.0, Python 3.11.3 (main, Apr 19 2023, 18:49:55) [Clang 14.0.6 ], pyOpenSSL 23.0.0 (OpenSSL 1.1.1w  11 Sep 2023), cryptography 39.0.1, Platform macOS-13.6.6-arm64-arm-64bit

2024-09-13 14:37:41 [scrapy.crawler] INFO: Overridden settings:

{'BOT_NAME': 'TweetScraper',

 'DOWNLOAD_DELAY': 1.0,

 'LOG_LEVEL': 'INFO',

 'NEWSPIDER_MODULE': 'TweetScraper.spiders',

 'SPIDER_MODULES': ['TweetScraper.spiders'],

 'USER_AGENT': ***@***.***'}

2024-09-13 14:37:41 [py.warnings] WARNING: /Users/bairuihuang/anaconda3/lib/python3.11/site-packages/scrapy/utils/request.py:232: ScrapyDeprecationWarning: '2.6' is a deprecated value for the 'REQUEST_FINGERPRINTER_IMPLEMENTATION' setting.




It is also the default value. In other words, it is normal to get this warning if you have not defined a value for the 'REQUEST_FINGERPRINTER_IMPLEMENTATION' setting. This is so for backward compatibility reasons, but it will change in a future version of Scrapy.




See the documentation of the 'REQUEST_FINGERPRINTER_IMPLEMENTATION' setting for information on how to handle this deprecation.

  return cls(crawler)




2024-09-13 14:37:41 [scrapy.extensions.telnet] INFO: Telnet Password: 06d64bffc92b2dce

2024-09-13 14:37:41 [scrapy.middleware] INFO: Enabled extensions:

['scrapy.extensions.corestats.CoreStats',

 'scrapy.extensions.telnet.TelnetConsole',

 'scrapy.extensions.memusage.MemoryUsage',

 'scrapy.extensions.logstats.LogStats']

Unhandled error in Deferred:

2024-09-13 14:37:41 [twisted] CRITICAL: Unhandled error in Deferred:




Traceback (most recent call last):

  File "/Users/bairuihuang/anaconda3/lib/python3.11/site-packages/scrapy/crawler.py", line 233, in crawl

    return self._crawl(crawler, *args, **kwargs)

  File "/Users/bairuihuang/anaconda3/lib/python3.11/site-packages/scrapy/crawler.py", line 237, in _crawl

    d = crawler.crawl(*args, **kwargs)

  File "/Users/bairuihuang/anaconda3/lib/python3.11/site-packages/twisted/internet/defer.py", line 1947, in unwindGenerator

    return _cancellableInlineCallbacks(gen)

  File "/Users/bairuihuang/anaconda3/lib/python3.11/site-packages/twisted/internet/defer.py", line 1857, in _cancellableInlineCallbacks

    _inlineCallbacks(None, gen, status, _copy_context())

--- <exception caught here> ---

  File "/Users/bairuihuang/anaconda3/lib/python3.11/site-packages/twisted/internet/defer.py", line 1697, in _inlineCallbacks

    result = context.run(gen.send, result)

  File "/Users/bairuihuang/anaconda3/lib/python3.11/site-packages/scrapy/crawler.py", line 122, in crawl

    self.engine = self._create_engine()

  File "/Users/bairuihuang/anaconda3/lib/python3.11/site-packages/scrapy/crawler.py", line 136, in _create_engine

    return ExecutionEngine(self, lambda _: self.stop())

  File "/Users/bairuihuang/anaconda3/lib/python3.11/site-packages/scrapy/core/engine.py", line 78, in __init__

    self.downloader = downloader_cls(crawler)

  File "/Users/bairuihuang/anaconda3/lib/python3.11/site-packages/scrapy/core/downloader/__init__.py", line 85, in __init__

    self.middleware = DownloaderMiddlewareManager.from_crawler(crawler)

  File "/Users/bairuihuang/anaconda3/lib/python3.11/site-packages/scrapy/middleware.py", line 68, in from_crawler

    return cls.from_settings(crawler.settings, crawler)

  File "/Users/bairuihuang/anaconda3/lib/python3.11/site-packages/scrapy/middleware.py", line 44, in from_settings

    mw = create_instance(mwcls, settings, crawler)

  File "/Users/bairuihuang/anaconda3/lib/python3.11/site-packages/scrapy/utils/misc.py", line 165, in create_instance

    instance = objcls.from_crawler(crawler, *args, **kwargs)

  File "/Users/bairuihuang/anaconda3/lib/python3.11/site-packages/scrapy_selenium/middlewares.py", line 67, in from_crawler

    middleware = cls(

  File "/Users/bairuihuang/anaconda3/lib/python3.11/site-packages/scrapy_selenium/middlewares.py", line 51, in __init__

    self.driver = driver_klass(**driver_kwargs)

builtins.TypeError: WebDriver.__init__() got an unexpected keyword argument 'executable_path'




2024-09-13 14:37:41 [twisted] CRITICAL: 

Traceback (most recent call last):

  File "/Users/bairuihuang/anaconda3/lib/python3.11/site-packages/twisted/internet/defer.py", line 1697, in _inlineCallbacks

    result = context.run(gen.send, result)

  File "/Users/bairuihuang/anaconda3/lib/python3.11/site-packages/scrapy/crawler.py", line 122, in crawl

    self.engine = self._create_engine()

  File "/Users/bairuihuang/anaconda3/lib/python3.11/site-packages/scrapy/crawler.py", line 136, in _create_engine

    return ExecutionEngine(self, lambda _: self.stop())

  File "/Users/bairuihuang/anaconda3/lib/python3.11/site-packages/scrapy/core/engine.py", line 78, in __init__

    self.downloader = downloader_cls(crawler)

  File "/Users/bairuihuang/anaconda3/lib/python3.11/site-packages/scrapy/core/downloader/__init__.py", line 85, in __init__

    self.middleware = DownloaderMiddlewareManager.from_crawler(crawler)

  File "/Users/bairuihuang/anaconda3/lib/python3.11/site-packages/scrapy/middleware.py", line 68, in from_crawler

    return cls.from_settings(crawler.settings, crawler)

  File "/Users/bairuihuang/anaconda3/lib/python3.11/site-packages/scrapy/middleware.py", line 44, in from_settings

    mw = create_instance(mwcls, settings, crawler)

  File "/Users/bairuihuang/anaconda3/lib/python3.11/site-packages/scrapy/utils/misc.py", line 165, in create_instance

    instance = objcls.from_crawler(crawler, *args, **kwargs)

  File "/Users/bairuihuang/anaconda3/lib/python3.11/site-packages/scrapy_selenium/middlewares.py", line 67, in from_crawler

    middleware = cls(

  File "/Users/bairuihuang/anaconda3/lib/python3.11/site-packages/scrapy_selenium/middlewares.py", line 51, in __init__

    self.driver = driver_klass(**driver_kwargs)

TypeError: WebDriver.__init__() got an unexpected keyword argument 'executable_path'




It seems that there is a problem in executable path, which is not usually used in recent days. Could you tell me how to solve it?




Best wishes,

Bairui Huang










At 2024-09-13 15:03:32, "nurdiafrianto" ***@***.***> wrote:

finish about what? can you explain

Pada Jum, 13 Sep 2024 pukul 12.29 HarrisonHHH ***@***.***>
menulis:

**Comment by nurdi1995** [comment]
have you tried with the latest version of scrapy? it seems the problem is
with the scrapy version

Pada Jum, 13 Sep 2024 pukul 15.08 HarrisonHHH ***@***.***>
menulis:

> Hi jonbakerfish,
>
>
>
>
> Thank you for your time.
>
>
>
>
> I encountered a new problem, which is
>
>
>
>
> (base) ***@***.*** TweetScraper % scrapy crawl TweetScraper -a
> query="foo,#bar"
>
> 2024-09-13 14:37:41 [scrapy.utils.log] INFO: Scrapy 2.8.0 started (bot:
> TweetScraper)
>
> 2024-09-13 14:37:41 [scrapy.utils.log] INFO: Versions: lxml 4.9.2.0,
> libxml2 2.10.3, cssselect 1.1.0, parsel 1.6.0, w3lib 1.21.0, Twisted
> 22.10.0, Python 3.11.3 (main, Apr 19 2023, 18:49:55) [Clang 14.0.6 ],
> pyOpenSSL 23.0.0 (OpenSSL 1.1.1w 11 Sep 2023), cryptography 39.0.1,
> Platform macOS-13.6.6-arm64-arm-64bit
>
> 2024-09-13 14:37:41 [scrapy.crawler] INFO: Overridden settings:
>
> {'BOT_NAME': 'TweetScraper',
>
> 'DOWNLOAD_DELAY': 1.0,
>
> 'LOG_LEVEL': 'INFO',
>
> 'NEWSPIDER_MODULE': 'TweetScraper.spiders',
>
> 'SPIDER_MODULES': ['TweetScraper.spiders'],
>
> 'USER_AGENT': ***@***.***'}
>
> 2024-09-13 14:37:41 [py.warnings] WARNING:
> /Users/bairuihuang/anaconda3/lib/python3.11/site-packages/scrapy/utils/request.py:232:
> ScrapyDeprecationWarning: '2.6' is a deprecated value for the
> 'REQUEST_FINGERPRINTER_IMPLEMENTATION' setting.
>
>
>
>
> It is also the default value. In other words, it is normal to get this
> warning if you have not defined a value for the
> 'REQUEST_FINGERPRINTER_IMPLEMENTATION' setting. This is so for backward
> compatibility reasons, but it will change in a future version of Scrapy.
>
>
>
>
> See the documentation of the 'REQUEST_FINGERPRINTER_IMPLEMENTATION'
> setting for information on how to handle this deprecation.
>
> return cls(crawler)
>
>
>
>
> 2024-09-13 14:37:41 [scrapy.extensions.telnet] INFO: Telnet Password:
> 06d64bffc92b2dce
>
> 2024-09-13 14:37:41 [scrapy.middleware] INFO: Enabled extensions:
>
> ['scrapy.extensions.corestats.CoreStats',
>
> 'scrapy.extensions.telnet.TelnetConsole',
>
> 'scrapy.extensions.memusage.MemoryUsage',
>
> 'scrapy.extensions.logstats.LogStats']
>
> Unhandled error in Deferred:
>
> 2024-09-13 14:37:41 [twisted] CRITICAL: Unhandled error in Deferred:
>
>
>
>
> Traceback (most recent call last):
>
> File
> "/Users/bairuihuang/anaconda3/lib/python3.11/site-packages/scrapy/crawler.py",
> line 233, in crawl
>
> return self._crawl(crawler, *args, **kwargs)
>
> File
> "/Users/bairuihuang/anaconda3/lib/python3.11/site-packages/scrapy/crawler.py",
> line 237, in _crawl
>
> d = crawler.crawl(*args, **kwargs)
>
> File
> "/Users/bairuihuang/anaconda3/lib/python3.11/site-packages/twisted/internet/defer.py",
> line 1947, in unwindGenerator
>
> return _cancellableInlineCallbacks(gen)
>
> File
> "/Users/bairuihuang/anaconda3/lib/python3.11/site-packages/twisted/internet/defer.py",
> line 1857, in _cancellableInlineCallbacks
>
> _inlineCallbacks(None, gen, status, _copy_context())
>
> --- <exception caught here> ---
>
> File
> "/Users/bairuihuang/anaconda3/lib/python3.11/site-packages/twisted/internet/defer.py",
> line 1697, in _inlineCallbacks
>
> result = context.run(gen.send, result)
>
> File
> "/Users/bairuihuang/anaconda3/lib/python3.11/site-packages/scrapy/crawler.py",
> line 122, in crawl
>
> self.engine = self._create_engine()
>
> File
> "/Users/bairuihuang/anaconda3/lib/python3.11/site-packages/scrapy/crawler.py",
> line 136, in _create_engine
>
> return ExecutionEngine(self, lambda _: self.stop())
>
> File
> "/Users/bairuihuang/anaconda3/lib/python3.11/site-packages/scrapy/core/engine.py",
> line 78, in __init__
>
> self.downloader = downloader_cls(crawler)
>
> File
> "/Users/bairuihuang/anaconda3/lib/python3.11/site-packages/scrapy/core/downloader/__init__.py",
> line 85, in __init__
>
> self.middleware = DownloaderMiddlewareManager.from_crawler(crawler)
>
> File
> "/Users/bairuihuang/anaconda3/lib/python3.11/site-packages/scrapy/middleware.py",
> line 68, in from_crawler
>
> return cls.from_settings(crawler.settings, crawler)
>
> File
> "/Users/bairuihuang/anaconda3/lib/python3.11/site-packages/scrapy/middleware.py",
> line 44, in from_settings
>
> mw = create_instance(mwcls, settings, crawler)
>
> File
> "/Users/bairuihuang/anaconda3/lib/python3.11/site-packages/scrapy/utils/misc.py",
> line 165, in create_instance
>
> instance = objcls.from_crawler(crawler, *args, **kwargs)
>
> File
> "/Users/bairuihuang/anaconda3/lib/python3.11/site-packages/scrapy_selenium/middlewares.py",
> line 67, in from_crawler
>
> middleware = cls(
>
> File
> "/Users/bairuihuang/anaconda3/lib/python3.11/site-packages/scrapy_selenium/middlewares.py",
> line 51, in __init__
>
> self.driver = driver_klass(**driver_kwargs)
>
> builtins.TypeError: WebDriver.__init__() got an unexpected keyword
> argument 'executable_path'
>
>
>
>
> 2024-09-13 14:37:41 [twisted] CRITICAL:
>
> Traceback (most recent call last):
>
> File
> "/Users/bairuihuang/anaconda3/lib/python3.11/site-packages/twisted/internet/defer.py",
> line 1697, in _inlineCallbacks
>
> result = context.run(gen.send, result)
>
> File
> "/Users/bairuihuang/anaconda3/lib/python3.11/site-packages/scrapy/crawler.py",
> line 122, in crawl
>
> self.engine = self._create_engine()
>
> File
> "/Users/bairuihuang/anaconda3/lib/python3.11/site-packages/scrapy/crawler.py",
> line 136, in _create_engine
>
> return ExecutionEngine(self, lambda _: self.stop())
>
> File
> "/Users/bairuihuang/anaconda3/lib/python3.11/site-packages/scrapy/core/engine.py",
> line 78, in __init__
>
> self.downloader = downloader_cls(crawler)
>
> File
> "/Users/bairuihuang/anaconda3/lib/python3.11/site-packages/scrapy/core/downloader/__init__.py",
> line 85, in __init__
>
> self.middleware = DownloaderMiddlewareManager.from_crawler(crawler)
>
> File
> "/Users/bairuihuang/anaconda3/lib/python3.11/site-packages/scrapy/middleware.py",
> line 68, in from_crawler
>
> return cls.from_settings(crawler.settings, crawler)
>
> File
> "/Users/bairuihuang/anaconda3/lib/python3.11/site-packages/scrapy/middleware.py",
> line 44, in from_settings
>
> mw = create_instance(mwcls, settings, crawler)
>
> File
> "/Users/bairuihuang/anaconda3/lib/python3.11/site-packages/scrapy/utils/misc.py",
> line 165, in create_instance
>
> instance = objcls.from_crawler(crawler, *args, **kwargs)
>
> File
> "/Users/bairuihuang/anaconda3/lib/python3.11/site-packages/scrapy_selenium/middlewares.py",
> line 67, in from_crawler
>
> middleware = cls(
>
> File
> "/Users/bairuihuang/anaconda3/lib/python3.11/site-packages/scrapy_selenium/middlewares.py",
> line 51, in __init__
>
> self.driver = driver_klass(**driver_kwargs)
>
> TypeError: WebDriver.__init__() got an unexpected keyword argument
> 'executable_path'
>
>
>
>
> It seems that there is a problem in executable path, which is not usually
> used in recent days. Could you tell me how to solve it?
>
>
>
>
> Best wishes,
>
> Bairui Huang
>
>
>
>
>
>
>
>
>
>
