### ISSUE TITLE
Windows 10 WSL, Selenium setup correctly, conda tweetscraper activated, WebDriverException status 0

### ISSUE THREAD

**Issue by irwanOyong** [jonbakerfish/TweetScraper#124]
Hello, thank you for the great work.

I faced an issue here, ran the mentioned installation of install.sh, finished flawlessly. 
But when I try to scrape some tweets, this is thrown.

`2021-04-08 09:19:44 [scrapy.utils.log] INFO: Scrapy 2.4.1 started (bot: TweetScraper)
2021-04-08 09:19:44 [scrapy.utils.log] INFO: Versions: lxml 4.6.3.0, libxml2 2.9.10, cssselect 1.1.0, parsel 1.6.0, w3lib 1.22.0, Twisted 21.2.0, Python 3.7.7 (default, May  7 2020, 21:25:33) - [GCC 7.3.0], pyOpenSSL 20.0.1 (OpenSSL 1.1.1k  25 Mar 2021), cryptography 3.4.7, Platform Linux-4.4.0-19041-Microsoft-x86_64-with-debian-bullseye-sid
2021-04-08 09:19:44 [scrapy.crawler] INFO: Overridden settings:
{'BOT_NAME': 'TweetScraper',
 'DOWNLOAD_DELAY': 1.0,
 'LOG_LEVEL': 'INFO',
 'NEWSPIDER_MODULE': 'TweetScraper.spiders',
 'SPIDER_MODULES': ['TweetScraper.spiders'],
 'USER_AGENT': 'TweetScraper'}
2021-04-08 09:19:44 [scrapy.extensions.telnet] INFO: Telnet Password: f957c9166e9361ff
2021-04-08 09:19:44 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.memusage.MemoryUsage',
 'scrapy.extensions.logstats.LogStats']
Unhandled error in Deferred:
2021-04-08 09:19:48 [twisted] CRITICAL: Unhandled error in Deferred:

Traceback (most recent call last):
  File "/home/airone/miniconda3/envs/tweetscraper/lib/python3.7/site-packages/scrapy/crawler.py", line 192, in crawl
    return self._crawl(crawler, *args, **kwargs)
  File "/home/airone/miniconda3/envs/tweetscraper/lib/python3.7/site-packages/scrapy/crawler.py", line 196, in _crawl
    d = crawler.crawl(*args, **kwargs)
  File "/home/airone/miniconda3/envs/tweetscraper/lib/python3.7/site-packages/twisted/internet/defer.py", line 1656, in unwindGenerator
    return _cancellableInlineCallbacks(gen)
  File "/home/airone/miniconda3/envs/tweetscraper/lib/python3.7/site-packages/twisted/internet/defer.py", line 1571, in _cancellableInlineCallbacks
    _inlineCallbacks(None, g, status)
--- <exception caught here> ---
  File "/home/airone/miniconda3/envs/tweetscraper/lib/python3.7/site-packages/twisted/internet/defer.py", line 1445, in _inlineCallbacks
    result = current_context.run(g.send, result)
  File "/home/airone/miniconda3/envs/tweetscraper/lib/python3.7/site-packages/scrapy/crawler.py", line 87, in crawl
    self.engine = self._create_engine()
  File "/home/airone/miniconda3/envs/tweetscraper/lib/python3.7/site-packages/scrapy/crawler.py", line 101, in _create_engine
    return ExecutionEngine(self, lambda _: self.stop())
  File "/home/airone/miniconda3/envs/tweetscraper/lib/python3.7/site-packages/scrapy/core/engine.py", line 69, in __init__
    self.downloader = downloader_cls(crawler)
  File "/home/airone/miniconda3/envs/tweetscraper/lib/python3.7/site-packages/scrapy/core/downloader/__init__.py", line 83, in __init__
    self.middleware = DownloaderMiddlewareManager.from_crawler(crawler)
  File "/home/airone/miniconda3/envs/tweetscraper/lib/python3.7/site-packages/scrapy/middleware.py", line 53, in from_crawler
    return cls.from_settings(crawler.settings, crawler)
  File "/home/airone/miniconda3/envs/tweetscraper/lib/python3.7/site-packages/scrapy/middleware.py", line 35, in from_settings
    mw = create_instance(mwcls, settings, crawler)
  File "/home/airone/miniconda3/envs/tweetscraper/lib/python3.7/site-packages/scrapy/utils/misc.py", line 167, in create_instance
    instance = objcls.from_crawler(crawler, *args, **kwargs)
  File "/home/airone/miniconda3/envs/tweetscraper/lib/python3.7/site-packages/scrapy_selenium/middlewares.py", line 71, in from_crawler
    browser_executable_path=browser_executable_path
  File "/home/airone/miniconda3/envs/tweetscraper/lib/python3.7/site-packages/scrapy_selenium/middlewares.py", line 51, in __init__
    self.driver = driver_klass(**driver_kwargs)
  File "/home/airone/miniconda3/envs/tweetscraper/lib/python3.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/home/airone/miniconda3/envs/tweetscraper/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/airone/miniconda3/envs/tweetscraper/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/airone/miniconda3/envs/tweetscraper/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/airone/miniconda3/envs/tweetscraper/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status 0`

Any insights? Thank you.

**Comment by happycjksh** [comment]
I have the same problem. Do you solve it?
