### ISSUE TITLE
AttributeError: module 'OpenSSL.SSL' has no attribute 'OP_SINGLE_ECDH_USE'

### ISSUE THREAD

**Issue by sunshengjing** [jonbakerfish/TweetScraper#25]
Hi,

when I run scrapy crawl TweetScraper -a query=foo,#bar, I got this error

AttributeError: module 'OpenSSL.SSL' has no attribute 'OP_SINGLE_ECDH_USE'

Can you tell how to solve it ?

Thanks 

>
Traceback (most recent call last):
  File "//anaconda/lib/python3.5/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "//anaconda/lib/python3.5/site-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "//anaconda/lib/python3.5/site-packages/scrapy/core/downloader/middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "//anaconda/lib/python3.5/site-packages/scrapy/utils/defer.py", line 45, in mustbe_deferred
    result = f(*args, **kw)
  File "//anaconda/lib/python3.5/site-packages/scrapy/core/downloader/handlers/__init__.py", line 65, in download_request
    return handler.download_request(request, spider)
  File "//anaconda/lib/python3.5/site-packages/scrapy/core/downloader/handlers/http11.py", line 63, in download_request
    return agent.download_request(request)
  File "//anaconda/lib/python3.5/site-packages/scrapy/core/downloader/handlers/http11.py", line 300, in download_request
    method, to_bytes(url, encoding='ascii'), headers, bodyproducer)
  File "//anaconda/lib/python3.5/site-packages/twisted/web/client.py", line 1649, in request
    endpoint = self._getEndpoint(parsedURI)
  File "//anaconda/lib/python3.5/site-packages/twisted/web/client.py", line 1633, in _getEndpoint
    return self._endpointFactory.endpointForURI(uri)
  File "//anaconda/lib/python3.5/site-packages/twisted/web/client.py", line 1510, in endpointForURI
    uri.port)
  File "//anaconda/lib/python3.5/site-packages/scrapy/core/downloader/contextfactory.py", line 59, in creatorForNetloc
    return ScrapyClientTLSOptions(hostname.decode("ascii"), self.getContext())
  File "//anaconda/lib/python3.5/site-packages/scrapy/core/downloader/contextfactory.py", line 56, in getContext
    return self.getCertificateOptions().getContext()
  File "//anaconda/lib/python3.5/site-packages/scrapy/core/downloader/contextfactory.py", line 51, in getCertificateOptions
    acceptableCiphers=DEFAULT_CIPHERS)
  File "//anaconda/lib/python3.5/site-packages/twisted/python/deprecate.py", line 792, in wrapped
    return wrappee(*args, **kwargs)
  File "//anaconda/lib/python3.5/site-packages/twisted/internet/_sslverify.py", line 1583, in __init__
    self._options |= SSL.OP_SINGLE_DH_USE | SSL.OP_SINGLE_ECDH_USE
AttributeError: module 'OpenSSL.SSL' has no attribute 'OP_SINGLE_ECDH_USE'

**Comment by jonbakerfish** [comment]
Didn't test on python 3.5
