### ISSUE TITLE
[twisted] CRITICAL: Unhandled error in Deferred

### ISSUE THREAD

**Issue by timotej-orcic** [jonbakerfish/TweetScraper#45]
Hi, before I post the issue I would like to say that your work on this project is superb!

As for the issue itself, I have used your scraper in the last 2-3 weeks and everything was working like a charm. But, when I started it yesterday it started throwing this exception. I tried to reinstall the dependencies, cloned the repo again, but nothing works. If you have any ideas how to solve this, I am thankful in advance.

Here is the full print of my action:
 scrapy crawl TweetScraper -a query='near:Chicago within:1mi since:2016-01-01
until:2016-12-31' -a lang='en'
2019-01-23 16:13:43 [scrapy.utils.log] INFO: Scrapy 1.5.1 started (bot: TweetScraper)
2019-01-23 16:13:43 [scrapy.utils.log] INFO: Versions: lxml 4.2.5.0, libxml2 2.9.8, cssselect 1.0.3, parsel 1.5.1, w3lib 1.19.0, Twisted 18.9.0, Python 3.7.1 (default, Dec 10 2018, 22:54:23) [MSC v.1915 64 bit (AMD64)], pyOpenSSL 18.0.0 (OpenSSL 1.1.1a  20 Nov 2018), cryptography 2.4.2, Platform Windows-10-10.0.17134-SP0
2019-01-23 16:13:43 [scrapy.crawler] INFO: Overridden settings: {'BOT_NAME': 'TweetScraper', 'LOG_LEVEL': 'INFO', 'NEWSPIDER_MODULE': 'TweetScraper.spiders', 'SPIDER_MODULES': ['TweetScraper.spiders'], 'USER_AGENT': 'XXXXXX'}
2019-01-23 16:13:43 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.logstats.LogStats']
2019-01-23 16:13:43 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2019-01-23 16:13:43 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
Unhandled error in Deferred:
2019-01-23 16:14:15 [twisted] CRITICAL: Unhandled error in Deferred:

Traceback (most recent call last):
  File "C:\Users\Tima\Anaconda3\lib\site-packages\scrapy\crawler.py", line 171, in crawl
    return self._crawl(crawler, *args, **kwargs)
  File "C:\Users\Tima\Anaconda3\lib\site-packages\scrapy\crawler.py", line 175, in _crawl
    d = crawler.crawl(*args, **kwargs)
  File "C:\Users\Tima\Anaconda3\lib\site-packages\twisted\internet\defer.py", line 1613, in unwindGenerator
    return _cancellableInlineCallbacks(gen)
  File "C:\Users\Tima\Anaconda3\lib\site-packages\twisted\internet\defer.py", line 1529, in _cancellableInlineCallbacks
    _inlineCallbacks(None, g, status)
--- <exception caught here> ---
  File "C:\Users\Tima\Anaconda3\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "C:\Users\Tima\Anaconda3\lib\site-packages\scrapy\crawler.py", line 80, in crawl
    self.engine = self._create_engine()
  File "C:\Users\Tima\Anaconda3\lib\site-packages\scrapy\crawler.py", line 105, in _create_engine
    return ExecutionEngine(self, lambda _: self.stop())
  File "C:\Users\Tima\Anaconda3\lib\site-packages\scrapy\core\engine.py", line 70, in __init__
    self.scraper = Scraper(crawler)
  File "C:\Users\Tima\Anaconda3\lib\site-packages\scrapy\core\scraper.py", line 71, in __init__
    self.itemproc = itemproc_cls.from_crawler(crawler)
  File "C:\Users\Tima\Anaconda3\lib\site-packages\scrapy\middleware.py", line 58, in from_crawler
    return cls.from_settings(crawler.settings, crawler)
  File "C:\Users\Tima\Anaconda3\lib\site-packages\scrapy\middleware.py", line 40, in from_settings
    mw = mwcls()
  File "C:\Users\Tima\Desktop\SIAP\TweetScraper\TweetScraper\pipelines.py", line 27, in __init__
    self.tweetCollection.ensure_index([('ID', pymongo.ASCENDING)], unique=True, dropDups=True)
  File "C:\Users\Tima\Anaconda3\lib\site-packages\pymongo\collection.py", line 1991, in ensure_index
    self.__create_index(keys, kwargs, session=None)
  File "C:\Users\Tima\Anaconda3\lib\site-packages\pymongo\collection.py", line 1847, in __create_index
    with self._socket_for_writes() as sock_info:
  File "C:\Users\Tima\Anaconda3\lib\site-packages\pymongo\collection.py", line 196, in _socket_for_writes
    return self.__database.client._socket_for_writes()
  File "C:\Users\Tima\Anaconda3\lib\site-packages\pymongo\mongo_client.py", line 1085, in _socket_for_writes
    server = self._get_topology().select_server(writable_server_selector)
  File "C:\Users\Tima\Anaconda3\lib\site-packages\pymongo\topology.py", line 224, in select_server
    address))
  File "C:\Users\Tima\Anaconda3\lib\site-packages\pymongo\topology.py", line 183, in select_servers
    selector, server_timeout, address)
  File "C:\Users\Tima\Anaconda3\lib\site-packages\pymongo\topology.py", line 199, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: connection closed,connection closed,connection closed

2019-01-23 16:14:15 [twisted] CRITICAL:
Traceback (most recent call last):
  File "C:\Users\Tima\Anaconda3\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "C:\Users\Tima\Anaconda3\lib\site-packages\scrapy\crawler.py", line 80, in crawl
    self.engine = self._create_engine()
  File "C:\Users\Tima\Anaconda3\lib\site-packages\scrapy\crawler.py", line 105, in _create_engine
    return ExecutionEngine(self, lambda _: self.stop())
  File "C:\Users\Tima\Anaconda3\lib\site-packages\scrapy\core\engine.py", line 70, in __init__
    self.scraper = Scraper(crawler)
  File "C:\Users\Tima\Anaconda3\lib\site-packages\scrapy\core\scraper.py", line 71, in __init__
    self.itemproc = itemproc_cls.from_crawler(crawler)
  File "C:\Users\Tima\Anaconda3\lib\site-packages\scrapy\middleware.py", line 58, in from_crawler
    return cls.from_settings(crawler.settings, crawler)
  File "C:\Users\Tima\Anaconda3\lib\site-packages\scrapy\middleware.py", line 40, in from_settings
    mw = mwcls()
  File "C:\Users\Tima\Desktop\SIAP\TweetScraper\TweetScraper\pipelines.py", line 27, in __init__
    self.tweetCollection.ensure_index([('ID', pymongo.ASCENDING)], unique=True, dropDups=True)
  File "C:\Users\Tima\Anaconda3\lib\site-packages\pymongo\collection.py", line 1991, in ensure_index
    self.__create_index(keys, kwargs, session=None)
  File "C:\Users\Tima\Anaconda3\lib\site-packages\pymongo\collection.py", line 1847, in __create_index
    with self._socket_for_writes() as sock_info:
  File "C:\Users\Tima\Anaconda3\lib\site-packages\pymongo\collection.py", line 196, in _socket_for_writes
    return self.__database.client._socket_for_writes()
  File "C:\Users\Tima\Anaconda3\lib\site-packages\pymongo\mongo_client.py", line 1085, in _socket_for_writes
    server = self._get_topology().select_server(writable_server_selector)
  File "C:\Users\Tima\Anaconda3\lib\site-packages\pymongo\topology.py", line 224, in select_server
    address))
  File "C:\Users\Tima\Anaconda3\lib\site-packages\pymongo\topology.py", line 183, in select_servers
    selector, server_timeout, address)
  File "C:\Users\Tima\Anaconda3\lib\site-packages\pymongo\topology.py", line 199, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: connection closed,connection closed,connection closed

**Comment by jonbakerfish** [comment]
It seems that the error is caused by the mongodb:

> pymongo.errors.ServerSelectionTimeoutError: connection closed

Can you check the connection or change the pipline to 

> 'TweetScraper.pipelines.SaveToFilePipeline':100

**Comment by timotej-orcic** [comment]
Yes, that was the problem, the FilePipeline works like a charm.

Thanks for your help, and on the effort on this project I really appreciate it. 

Cheers! :)
