### ISSUE TITLE
Error: Error downloading <GET https://twitter.com/i/search/timeline?l=&f=tweets&q=Trump&src=typed&max_position=>

### ISSUE THREAD

**Issue by abrahamali** [jonbakerfish/TweetScraper#55]
When giving the command as: scrapy crawl Tweetscraper -a query=Trump , it throws error. 
ERROR: Error downloading <GET https://twitter.com/i/search/timeline?l=&f=tweets&q=Trump&src=typed&max_position=>

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1126, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/core/downloader/middleware.py", line 37, in process_request
    response = yield method(request=request, spider=spider)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/downloadermiddlewares/robotstxt.py", line 46, in process_request_2
    if not rp.can_fetch(to_native_str(self._useragent), request.url):
  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/python.py", line 129, in to_native_str
    return to_bytes(text, encoding, errors)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/python.py", line 119, in to_bytes
    'object, got %s' % type(text).__name__)
TypeError: to_bytes must receive a unicode, str or bytes object, got list
2019-07-16 14:27:59 [scrapy.core.engine] INFO: Closing spider (finished)

**Comment by jonbakerfish** [comment]
Use python3
