### ISSUE TITLE
Exception Error:

### ISSUE THREAD

**Issue by banyous** [jonbakerfish/TweetScraper#56]

**Comment by banyous** [comment]
Whenever I run the two codes provided in the main page :

>>> for tweet in get_tweets('kennethreitz', pages=1):
>>>     print(tweet['text'])

or 

>>> tweets = '\n'.join([t['text'] for t in get_tweets('kennethreitz', pages=25)])

I get the error message : 
>>> tweets = '\n'.join([t['text'] for t in get_tweets('adam', pages=25)])
Traceback (most recent call last):
  File "/home/karim/Documents/Github/twitter-scraper/twitter_scraper.py", line 38, in gen_tweets
    html = HTML(html=r.json()['items_html'],
KeyError: 'items_html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 1, in <listcomp>
  File "/home/karim/Documents/Github/twitter-scraper/twitter_scraper.py", line 134, in get_tweets
    yield from gen_tweets(pages)
  File "/home/karim/Documents/Github/twitter-scraper/twitter_scraper.py", line 42, in gen_tweets
    'Oops! Either "{query}" does not exist or is private.')
ValueError: Oops! Either "{query}" does not exist or is private.


Please advice
