### ISSUE TITLE
ImportError: No module named configparser

### ISSUE THREAD

**Issue by jeromecc** [jonbakerfish/TweetScraper#59]
It looks like TweetScraper, after installing all requirements in a Python 2.7 virtual environment, is still missing configparser.
Should we add it to the requirements file?
```
(TweetScraper) elkcloner@debian:~/git/DocTocToc/TweetScraper/TweetScraper$ scrapy list
Traceback (most recent call last):
  File "/home/elkcloner/.virtualenvs/TweetScraper/bin/scrapy", line 6, in <module>
    from scrapy.cmdline import execute
  File "/home/elkcloner/.virtualenvs/TweetScraper/local/lib/python2.7/site-packages/scrapy/cmdline.py", line 10, in <module>
    from scrapy.crawler import CrawlerProcess
  File "/home/elkcloner/.virtualenvs/TweetScraper/local/lib/python2.7/site-packages/scrapy/crawler.py", line 11, in <module>
    from scrapy.core.engine import ExecutionEngine
  File "/home/elkcloner/.virtualenvs/TweetScraper/local/lib/python2.7/site-packages/scrapy/core/engine.py", line 14, in <module>
    from scrapy.core.scraper import Scraper
  File "/home/elkcloner/.virtualenvs/TweetScraper/local/lib/python2.7/site-packages/scrapy/core/scraper.py", line 18, in <module>
    from scrapy.core.spidermw import SpiderMiddlewareManager
  File "/home/elkcloner/.virtualenvs/TweetScraper/local/lib/python2.7/site-packages/scrapy/core/spidermw.py", line 13, in <module>
    from scrapy.utils.conf import build_component_list
  File "/home/elkcloner/.virtualenvs/TweetScraper/local/lib/python2.7/site-packages/scrapy/utils/conf.py", line 4, in <module>
    import configparser
ImportError: No module named configparser
(TweetScraper) elkcloner@debian:~/git/DocTocToc/TweetScraper/TweetScraper$ pip install configparser
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.                                                                                                                                    
Collecting configparser
  Using cached https://files.pythonhosted.org/packages/ba/05/6c96328e92e625fc31445d24d75a2c92ef9ba34fc5b037fe69693c362a0d/configparser-3.7.4-py2.py3-none-any.whl
Installing collected packages: configparser
Successfully installed configparser-3.7.4
(TweetScraper) elkcloner@debian:~/git/DocTocToc/TweetScraper/TweetScraper$ scrapy list
TweetScraper
```

**Comment by jonbakerfish** [comment]
Thanks for reminding.
