### ISSUE TITLE
tweetscraper dosn't save the output to file

### ISSUE THREAD

**Issue by smycek** [jonbakerfish/TweetScraper#65]
While i can see the requests TweetScraper processes, TS isn't able to save the output in `./Data/tweet`.

I get this error message when TweetScraper processes the query:

`Traceback (most recent call last):
  File "/Users/me/Library/Python/2.7/lib/python/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/Users/me/my/ts/dir/TweetScraper/TweetScraper/pipelines.py", line 187, in process_item
    self.save_to_file(item,savePath)
  File "/Users/me/my/ts/dir/TweetScraper/TweetScraper/pipelines.py", line 210, in save_to_file
    with open(fname,'w', encoding='utf-8') as f:
TypeError: 'encoding' is an invalid keyword argument for this function`

**Comment by smycek** [comment]
> While i can see the requests TweetScraper processes, TS isn't able to save the output in `./Data/tweet`.
> 
> I get this error message when TweetScraper processes the query:
> 
> `Traceback (most recent call last): File "/Users/me/Library/Python/2.7/lib/python/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks current.result = callback(current.result, *args, **kw) File "/Users/me/my/ts/dir/TweetScraper/TweetScraper/pipelines.py", line 187, in process_item self.save_to_file(item,savePath) File "/Users/me/my/ts/dir/TweetScraper/TweetScraper/pipelines.py", line 210, in save_to_file with open(fname,'w', encoding='utf-8') as f: TypeError: 'encoding' is an invalid keyword argument for this function`

My locale was accidentally not configured since i edited my .zshrc few hours ago. 🤦🏻‍♂️
`export LANG=en_US.UTF-8` did the trick ;)
