### ISSUE TITLE
keyerror

### ISSUE THREAD

**Issue by ihahawen** [jonbakerfish/TweetScraper#98]
2020-10-03 23:43:32 [scrapy.core.scraper] ERROR: Spider error processing <GET https://twitter.com/explore> (referer: None)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/scrapy/utils/defer.py", line 120, in iter_errback
    yield next(it)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/scrapy/utils/python.py", line 347, in __next__
    return next(self.data)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/scrapy/utils/python.py", line 347, in __next__
    return next(self.data)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/scrapy/core/spidermw.py", line 64, in _evaluate_iterable
    for r in iterable:
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/scrapy/core/spidermw.py", line 64, in _evaluate_iterable
    for r in iterable:
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/scrapy/spidermiddlewares/referer.py", line 340, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/scrapy/core/spidermw.py", line 64, in _evaluate_iterable
    for r in iterable:
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/scrapy/core/spidermw.py", line 64, in _evaluate_iterable
    for r in iterable:
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/scrapy/core/spidermw.py", line 64, in _evaluate_iterable
    for r in iterable:
  File "/Users/333/Documents/GitHub/TweetScraper/TweetScraper/spiders/TweetCrawler.py", line 69, in parse_home_page
    self.update_cookies(response)
  File "/Users/333/Documents/GitHub/TweetScraper/TweetScraper/spiders/TweetCrawler.py", line 75, in update_cookies
    driver = response.meta['driver']
KeyError: 'driver'
2020-10-03 23:43:32 [scrapy.core.engine] INFO: Closing spider (finished)
2020-10-03 23:43:32 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 196,
 'downloader/request_count': 1,
 'downloader/request_method_count/GET': 1,
 'downloader/response_bytes': 16668,
 'downloader/response_count': 1,
 'downloader/response_status_count/200': 1,
 'elapsed_time_seconds': 13.731425,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2020, 10, 3, 15, 43, 32, 358149),
 'log_count/ERROR': 1,
 'log_count/INFO': 10,
 'log_count/WARNING': 1,
 'memusage/max': 52822016,
 'memusage/startup': 52822016,
 'response_received_count': 1,
 'scheduler/dequeued': 1,
 'scheduler/dequeued/memory': 1,
 'scheduler/enqueued': 1,
 'scheduler/enqueued/memory': 1,
 'spider_exceptions/KeyError': 1,
 'start_time': datetime.datetime(2020, 10, 3, 15, 43, 18, 626724)}
2020-10-03 23:43:32 [scrapy.core.engine] INFO: Spider closed (finished)

**Comment by ihahawen** [comment]
i use mac,now i use"brew install geckodriver" ,I don't know if I can solve the problem

**Comment by jonbakerfish** [comment]
please follow https://selenium-python.readthedocs.io/installation.html to set up selenium properly
